<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%order_cleaning}}`.
 */
class m260113_150000_create_order_cleaning_table extends Migration
{
    private $tableName = 'order_cleaning';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name' => $this->string(255)->notNull(),
            'service_type_id' => $this->integer()->notNull(),
            'quantity' => $this->integer()->notNull()->defaultValue(1),
            'detail_member' => $this->json()->notNull()->defaultValue(json_encode([])),
            'detail_address' => $this->json()->notNull()->defaultValue(json_encode([])),
            'location_detail' => $this->json()->notNull()->defaultValue(json_encode([])),
            'unit_detail' => $this->json()->notNull()->defaultValue(json_encode([])),
            'schedule_detail' => $this->json()->notNull()->defaultValue(json_encode([])),
            'price' => $this->float()->null(),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'service_type' => [],
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $initialData = [
            [
                'name' => 'NRML-15641564',
                'service_type_id' => 1,
                'quantity' => 2,
                'detail_member' => [
                    'name' => 'John Doe',
                    'email' => 'john.doe@example.com',
                    'phone' => [
                        '6281122223412',
                    ],
                    'avatar' => null,
                    'gender' => null,
                    'birth_date' => null,
                ],
                'detail_address' => [
                    'address' => 'Ruko Madison Grande Blok J No. 66',
                    'city' => 'Kabupaten Tangerang',
                    'district' => 'Pagedangan',
                    'sub_district' => 'Medang',
                    'zip_code' => '15331',
                    'location' => [
                        'lat' => -6.270097,
                        'lng' => 106.624070,
                    ],
                ],
                'location_detail' => [
                    'floor' => 1,
                    'parking_available' => true,
                    'location_type' => 'Rumah',
                    'note' => 'Mohon teknisi membawa tangga. Kucing di rumah.',
                ],
                'unit_detail' => [
                    [
                        'brand' => [
                            'id' => 2,
                            'name' => 'Gree',
                        ],
                        'type' => [
                            'id' => 1,
                            'name' => 'Split Wall - Standard',
                        ],
                        'power' => 1,
                        'description' => 'Kurang dingin',
                    ],
                    [
                        'brand' => [
                            'id' => 1,
                            'name' => 'Sharp',
                        ],
                        'type' => [
                            'id' => 1,
                            'name' => 'Split Wall - Standard',
                        ],
                        'power' => 0.5,
                        'description' => 'Bau tidak sedap',
                    ],
                ],
                'schedule_detail' => [
                    'date' => '2026-01-15',
                    'time_range' => '09:00-12:00',
                ],
                'price' => 150000,
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'service_type' => [
                        'id' => 1,
                        'name' => 'Normal Cleaning',
                        'estimated_duration' => 60,
                        'detail_service' => [
                            'services' => [
                                'Pembersihan filter udara',
                                'Pembersihan evaporator dengan chemical khusus',
                                'Pembersihan blower fan',
                                'Pembersihan drainase',
                                'Pemeriksaan tekanan freon',
                            ],
                            'includes' => [
                                'Chemical pembersih',
                                'Pengecekan kondisi AC',
                                'Test fungsionalitas',
                            ],
                            'excludes' => [
                                'Penambahan freon',
                                'Spare part replacement',
                                'Perbaikan kerusakan',
                            ],
                            'recommended_for' => 'AC yang digunakan rutin 2-3 bulan terakhir',
                        ],
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'GNRL-846514658',
                'service_type_id' => 2,
                'quantity' => 1,
                'detail_member' => [
                    'name' => 'John Doe',
                    'email' => 'john.doe@example.com',
                    'phone' => [
                        '6281122223412',
                    ],
                    'avatar' => null,
                    'gender' => null,
                    'birth_date' => null,
                ],
                'detail_address' => [
                    'address' => 'Ruko Madison Grande Blok J No. 66',
                    'city' => 'Kabupaten Tangerang',
                    'district' => 'Pagedangan',
                    'sub_district' => 'Medang',
                    'zip_code' => '15331',
                    'location' => [
                        'lat' => -6.270097,
                        'lng' => 106.624070,
                    ],
                ],
                'location_detail' => [
                    'floor' => 2,
                    'parking_available' => true,
                    'location_type' => 'Rumah',
                    'note' => 'Mohon teknisi membawa tangga. Kucing di rumah.',
                ],
                'unit_detail' => [
                    [
                        'brand' => [
                            'id' => 2,
                            'name' => 'Gree',
                        ],
                        'type' => [
                            'id' => 1,
                            'name' => 'Split Wall - Standard',
                        ],
                        'power' => 2,
                        'description' => 'Kurang dingin',
                    ],
                ],
                'schedule_detail' => [
                    'date' => '2026-01-16',
                    'time_range' => '09:00-12:00',
                ],
                'price' => 250000,
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'service_type' => [
                        'id' => 1,
                        'name' => 'Normal Cleaning',
                        'estimated_duration' => 90,
                        'detail_service' => [
                            'services' => [
                                'Pembongkaran unit indoor',
                                'Pembersihan evaporator dengan steam cleaning',
                                'Pembersihan blower fan secara menyeluruh',
                                'Pembersihan filter udara dengan chemical',
                                'Pembersihan drainase dan pipa pembuangan',
                                'Pembersihan casing indoor dan outdoor',
                                'Pemeriksaan kompresor dan kelistrikan',
                                'Kalibrasi thermostat',
                            ],
                            'includes' => [
                                'Chemical pembersih premium',
                                'Steam cleaning equipment',
                                'Pengecekan lengkap sistem',
                                'Test fungsionalitas menyeluruh',
                                'Garansi 30 hari untuk hasil pembersihan',
                            ],
                            'excludes' => [
                                'Penambahan freon (biaya tambahan)',
                                'Spare part replacement',
                                'Perbaikan kerusakan komponen',
                            ],
                            'recommended_for' => 'AC yang jarang dibersihkan (>6 bulan) atau mengalami masalah kinerja',
                        ],
                    ],
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
