<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%order_installation}}`.
 */
class m260114_100000_create_order_installation_table extends Migration
{
    private $tableName = 'order_installation';

    public function safeUp()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $mongodb_param = require(\Yii::getAlias('@app/config/mongodb.php'));
        $UTCTimestamp = gmdate($params['timestamp']['UTC']);
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->createTable('{{%' . $this->tableName . '}}', [
            'id' => $this->integer()->append('PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'),
            'name' => $this->string(100)->notNull(),
            'service_type' => $this->string(50)->notNull()->comment('package or non_package'),
            'pipe_grade' => $this->string(50)->null()->comment('premium or luxury for package service'),
            'pipe_length' => $this->string(50)->null()->comment('3M or 5M for package service'),
            'base_price' => $this->float()->notNull()->defaultValue(0),
            'estimated_duration' => $this->integer()->null()->comment('Duration in minutes'),
            'detail_service' => $this->json()->notNull()->defaultValue(json_encode([])),
            'status' => $this->smallInteger()->notNull()->defaultValue($dbDefault['status'])->comment($dbDefault['statusComment']),
            'detail_info' => $this->json()->notNull()->defaultValue(json_encode([
                'change_log' => [
                    'created_at' => null,
                    'created_by' => null,
                    'deleted_at' => null,
                    'deleted_by' => null,
                    'updated_at' => null,
                    'updated_by' => null,
                ],
            ])),
        ]);

        $initialData = [
            // Package Services - Premium Grade
            [
                'name' => 'Paket Premium 3M',
                'service_type' => 'package',
                'pipe_grade' => 'premium',
                'pipe_length' => '3M',
                'base_price' => 350000,
                'estimated_duration' => 120,
                'detail_service' => [
                    'services' => [
                        'Jasa Pasang AC Baru',
                        'Pipa Tembaga AC Premium Grade 3 Meter',
                        'Kabel Kontrol AC',
                        'Pipa Drain',
                        'Bracket Outdoor',
                        'Duct Tape',
                    ],
                    'includes' => [
                        'Free Bobok Ceplos',
                        'Free Vakum AC',
                        'Garansi pemasangan 30 hari',
                        'Pengecekan fungsionalitas',
                    ],
                    'excludes' => [
                        'Penambahan freon (biaya tambahan)',
                        'Spare part replacement',
                        'Perbaikan kerusakan existing',
                    ],
                    'recommended_for' => 'Pemasangan AC baru dengan pipa premium grade',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'Paket Premium 5M',
                'service_type' => 'package',
                'pipe_grade' => 'premium',
                'pipe_length' => '5M',
                'base_price' => 450000,
                'estimated_duration' => 150,
                'detail_service' => [
                    'services' => [
                        'Jasa Pasang AC Baru',
                        'Pipa Tembaga AC Premium Grade 5 Meter',
                        'Kabel Kontrol AC',
                        'Pipa Drain',
                        'Bracket Outdoor',
                        'Duct Tape',
                    ],
                    'includes' => [
                        'Free Bobok Ceplos',
                        'Free Vakum AC',
                        'Garansi pemasangan 30 hari',
                        'Pengecekan fungsionalitas',
                    ],
                    'excludes' => [
                        'Penambahan freon (biaya tambahan)',
                        'Spare part replacement',
                        'Perbaikan kerusakan existing',
                    ],
                    'recommended_for' => 'Pemasangan AC baru dengan pipa premium grade panjang 5 meter',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            // Package Services - Luxury Grade
            [
                'name' => 'Paket Luxury 3M',
                'service_type' => 'package',
                'pipe_grade' => 'luxury',
                'pipe_length' => '3M',
                'base_price' => 450000,
                'estimated_duration' => 120,
                'detail_service' => [
                    'services' => [
                        'Jasa Pasang AC Baru',
                        'Pipa Tembaga AC Luxury Grade 3 Meter',
                        'Kabel Kontrol AC',
                        'Pipa Drain',
                        'Bracket Outdoor',
                        'Duct Tape',
                    ],
                    'includes' => [
                        'Free Bobok Ceplos',
                        'Free Vakum AC',
                        'Garansi pemasangan 60 hari',
                        'Pengecekan fungsionalitas',
                        'Pipe insulation premium',
                    ],
                    'excludes' => [
                        'Penambahan freon (biaya tambahan)',
                        'Spare part replacement',
                        'Perbaikan kerusakan existing',
                    ],
                    'recommended_for' => 'Pemasangan AC baru dengan pipa luxury grade kualitas terbaik',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'Paket Luxury 5M',
                'service_type' => 'package',
                'pipe_grade' => 'luxury',
                'pipe_length' => '5M',
                'base_price' => 550000,
                'estimated_duration' => 150,
                'detail_service' => [
                    'services' => [
                        'Jasa Pasang AC Baru',
                        'Pipa Tembaga AC Luxury Grade 5 Meter',
                        'Kabel Kontrol AC',
                        'Pipa Drain',
                        'Bracket Outdoor',
                        'Duct Tape',
                    ],
                    'includes' => [
                        'Free Bobok Ceplos',
                        'Free Vakum AC',
                        'Garansi pemasangan 60 hari',
                        'Pengecekan fungsionalitas',
                        'Pipe insulation premium',
                    ],
                    'excludes' => [
                        'Penambahan freon (biaya tambahan)',
                        'Spare part replacement',
                        'Perbaikan kerusakan existing',
                    ],
                    'recommended_for' => 'Pemasangan AC baru dengan pipa luxury grade kualitas terbaik panjang 5 meter',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            // Non-Package Services
            [
                'name' => 'Jasa Pasang AC Baru',
                'service_type' => 'non_package',
                'pipe_grade' => null,
                'pipe_length' => null,
                'base_price' => 150000,
                'estimated_duration' => 90,
                'detail_service' => [
                    'services' => [
                        'Jasa pemasangan unit AC',
                        'Pengecekan kelistrikan',
                        'Pemasangan bracket outdoor',
                        'Testing fungsionalitas',
                    ],
                    'includes' => [
                        'Garansi pemasangan 30 hari',
                        'Pengecekan kondisi AC',
                    ],
                    'excludes' => [
                        'Material pipa, kabel, bracket',
                        'Penambahan freon',
                        'Bobok tembok',
                    ],
                    'recommended_for' => 'Jasa pemasangan saja (material disediakan customer)',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'Pipa AC Premium',
                'service_type' => 'non_package',
                'pipe_grade' => 'premium',
                'pipe_length' => 'per_meter',
                'base_price' => 45000,
                'estimated_duration' => 30,
                'detail_service' => [
                    'services' => [
                        'Pipa tembaga AC premium grade',
                        'Potong dan sambung pipa',
                    ],
                    'includes' => [
                        'Pipa tembaga premium grade',
                        'Pemasangan pipa',
                    ],
                    'excludes' => [
                        'Jasa pemasangan AC',
                        'Material lainnya',
                    ],
                    'recommended_for' => 'Pembelian pipa premium grade per meter',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'Pipa AC Luxury',
                'service_type' => 'non_package',
                'pipe_grade' => 'luxury',
                'pipe_length' => 'per_meter',
                'base_price' => 65000,
                'estimated_duration' => 30,
                'detail_service' => [
                    'services' => [
                        'Pipa tembaga AC luxury grade',
                        'Potong dan sambung pipa',
                    ],
                    'includes' => [
                        'Pipa tembaga luxury grade',
                        'Pemasangan pipa',
                        'Pipe insulation premium',
                    ],
                    'excludes' => [
                        'Jasa pemasangan AC',
                        'Material lainnya',
                    ],
                    'recommended_for' => 'Pembelian pipa luxury grade per meter',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'Jasa Tarik Pipa',
                'service_type' => 'non_package',
                'pipe_grade' => null,
                'pipe_length' => null,
                'base_price' => 150000,
                'estimated_duration' => 60,
                'detail_service' => [
                    'services' => [
                        'Jasa penarikan pipa AC',
                        'Bobok tembok (jika diperlukan)',
                        'Penyambungan pipa',
                    ],
                    'includes' => [
                        'Jasa tarik pipa',
                        'Bobok tembok minimal',
                    ],
                    'excludes' => [
                        'Material pipa',
                        'Material lainnya',
                    ],
                    'recommended_for' => 'Jasa penarikan pipa untuk instalasi',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
            [
                'name' => 'Kabel AC Isi 3',
                'service_type' => 'non_package',
                'pipe_grade' => null,
                'pipe_length' => null,
                'base_price' => 75000,
                'estimated_duration' => 30,
                'detail_service' => [
                    'services' => [
                        'Kabel AC 3 core',
                        'Pemasangan kabel',
                    ],
                    'includes' => [
                        'Kabel AC 3 core',
                        'Pemasangan kabel',
                    ],
                    'excludes' => [
                        'Jasa pemasangan AC',
                        'Material lainnya',
                    ],
                    'recommended_for' => 'Pembelian kabel AC 3 core',
                ],
                'status' => $dbDefault['status'],
                'detail_info' => [
                    'change_log' => [
                        'created_at' => $UTCTimestamp,
                        'created_by' => $dbDefault['createdBy'],
                        'deleted_at' => null,
                        'deleted_by' => null,
                        'updated_at' => null,
                        'updated_by' => null,
                    ],
                ],
            ],
        ];

        foreach ($initialData as $value) {
            $this->insert('{{%' . $this->tableName . '}}', $value);
        }
    }

    public function safeDown()
    {
        $params = require(\Yii::getAlias('@app/config/params.php'));
        $dbDefault = $params['dbDefault'];

        if (!YII_ENV_DEV) {
            echo $dbDefault['skipMigrateFresh'];
            return true;
        }

        $this->dropTable('{{%' . $this->tableName . '}}');
    }
}
